// Public entry point for @chakra-ui/vue.
//
// The styling runtime is generated by PandaCSS (see panda.config.ts) into
// `src/styled-system` — the `chakra` factory, `css`/`cva`/`sva`,
// `createStyleContext`, token access, and layout patterns. This entry
// re-exports that generated surface (plus the theme) as the package's public
// API, mirroring the runtime pieces of @chakra-ui/react's own public
// `styled-system` exports. Emotion-era runtime constructs (`createSystem`,
// the `SystemContext`-based `ChakraProvider`/`useToken`) have no Panda
// equivalent — global CSS ships as a static `styles.css`, resolved at build
// time rather than injected at runtime.

// The `chakra` factory, generated layout components (Box, Flex, Stack, …),
// `createStyleContext` for wrapping multi-part (Ark) components, and prop
// helpers (`isCssProperty`, `splitCssProps`). This barrel also carries the
// component-facing jsx types (HTMLChakraProps, ChakraComponent, etc.).
export * from "./styled-system/jsx"

// Style authoring: `css`, `cva`, `sva`, `cx`, `mergeCss`.
export * from "./styled-system/css"

// Token access: `token(path, fallback)` and `token.var`.
export * from "./styled-system/tokens"

// Layout pattern fns (aspectRatio, container, grid, …) — the functional
// counterparts to the generated pattern components already re-exported by jsx.
export * from "./styled-system/patterns"

// Public styling types not surfaced through the jsx barrel — the style-object
// and conditional-value types used to author `css()` calls and recipes.
export type {
  SystemStyleObject,
  ConditionalValue,
  SystemProperties,
  CssProperties,
  GlobalStyleObject,
} from "./styled-system/types"

// The default Chakra theme (tokens, recipes, semantic tokens) and its Panda
// preset form, for consumers extending the theme via their own Panda config.
export * from "./theme"

// Component slot/part anatomy definitions (sourced from @ark-ui/vue).
export * from "./anatomy"
