name: Quality (Vue)

on:
  push:
    branches:
      - feature/**
      - main
    paths:
      - "packages/vue/**"
      - "vite.config.ts"
      - "vitest.setup.ts"
      - ".eslintrc*"
      - "eslint.config.*"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/quality-vue.yml"
  pull_request:
    branches:
      - feature/**
      - main
    paths:
      - "packages/vue/**"
      - "vite.config.ts"
      - "vitest.setup.ts"
      - ".eslintrc*"
      - "eslint.config.*"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/quality-vue.yml"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Build @chakra-ui/vue
        run: pnpm --filter @chakra-ui/vue build

  types:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run typecheck
        run: pnpm --filter @chakra-ui/vue typecheck

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run tests
        run: pnpm vitest run packages/vue

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run ESLint
        run: pnpm eslint packages/vue --ext .ts,.tsx --cache

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run prettier
        run: pnpm prettier --check packages/vue --cache
